### PR TITLE
Fix issue with duplicate json keys in sql query result

### LINKED ISSUE #67: cda-service overwrites query columns with same name
The following demonstrates how patient id becomes substituted with the subject id. The query includes both the 

```
two_id_query = '''select p.id ,  s1.id
    FROM gdc-bq-sample.cda_mvp.v3 p,
    unnest(ResearchSubject) as s1,
    UNNEST(s1.identifier) as i1,
    UNNEST(s1.Diagnosis) as d1
    where i1.system ='GDC' 
    order by p.id '''
api_instance.sql_query('v3',two_id_query,
                      limit=10)
```
gives
```[{'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad'},
  {'id': 'e6915db0-7c89-484d-8f9f-15cca68b82fc'},
  {'id': '16614d46-172b-479c-992b-e80a8e9a2c59'},
  {'id': '567fc9e3-17a6-42b1-a896-5e9a9507d1d8'},
  {'id': '54e89878-a1bc-4f5a-9d68-4842a469586e'},
  {'id': 'a1c7b7b9-b8c8-48c3-9420-55497f9318fd'},
  {'id': 'ce3c8b98-e275-4cfd-a379-940d675a564b'},
  {'id': 'e4ce89ef-bcaa-418a-8a6b-3602793b9bbf'},
  {'id': '19d3c861-8a5f-49a2-acc0-b55b25465c35'},
  {'id': 'afae8dce-294a-4108-bb28-376f804ae5c4'}]
```

Only a single column is shown in the results. If a query like this is run directly in the BigQuery API then two columns are returned. The second column is automatically named 'id_1' by BigQuery.

It seems that the CDA parses the BigQuery results and treats both columns as id, overwriting p.id with s.id.

This likely explains why the patient id contained the subject id in https://github.com/CancerDataAggregator/cda-python/issues/16

The following confirms that the problem occurs for another query showing that it misses other columns with the same name

```
select p.id ,  su.id, su_id.system, su_id.value, sp_id.system, sp_id.value
    FROM gdc-bq-sample.cda_mvp.v3 p,
    unnest(ResearchSubject) as su,
    UNNEST(su.Identifier) as su_id,
    unnest(Specimen) as sp,
    UNNEST(sp.Identifier) as sp_id
    order by p.id
```

returns only one each of system and value

```
[{'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '41d6aa10-181a-47cc-8eb5-3a28a8421a7d'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '65be1f28-b428-59e5-a187-22335ec57c17'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '786c67dd-7425-5804-97ce-7b64e96569c1'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '49602e48-0ccf-5f3c-9529-255fc3f3368f'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '7c2a9d5c-2315-57bd-ade5-e0932b421b0e'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': 'e0c6965b-fe8a-4ada-bf8f-c6a00d506ecd'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '721645ba-916b-5481-bf76-63891cb79836'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': 'dcc36b6e-7743-40b4-98eb-06580a694e0e'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '3ae5c716-7061-4236-8a90-bddc4e6e4834'},
  {'id': 'be37f1f7-2f98-4f74-bc04-6dd2ae2afcad',
   'system': 'GDC',
   'value': '14fbb898-2e88-5dd5-b7f6-6783a89754f4'}]
```

### PR DESCRIPTION
**Pull request by pshapiro4broad**
SQL Query results that would previously have duplicate keys now have unique names for each key. The order and naming of the keys is not guaranteed to be stable between queries.

Fixes #67

### CODE REVIEW

File: src/main/java/bio/terra/cda/app/service/QueryService.java [hunk 1]
```diff
@@ -79,12 +80,19 @@ private Results getJobResults(Job queryJob) {
...
+      // Copy all row data to results. For each row, collect the fields as JSON key/value pairs.
       for (FieldValueList row : result.iterateAll()) {
-        var rowData = row.get(0).getStringValue();
+        List<String> fieldData = new ArrayList<>();
+        for (int i = 0; i < fields.size(); i++) {
+          fieldData.add(
+              String.format(
+                  "\"%s\":\"%s\"\n", fields.get(i).getName(), row.get(i).getStringValue()));
+        }
+        String rowData = "{" + String.join(",", fieldData) + "}";
```
Comment (nmalfroy) [inline src/main/java/bio/terra/cda/app/service/QueryService.java:95]: Would it be safer to use something like Jackson to serialize the Json?  You'd save yourself from potential encoding issues.

**Comment by pshapiro4broad** [comment]
Let me give it a try. With the current code the field is RawJson. Making it
a real json object could make that simpler too.

File: src/main/java/bio/terra/cda/app/service/QueryService.java (hunk 1 above)
Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java]: That was a great idea, by changing this to use a json object I was able to remove the RawJsonValue hack I added in a while back.

Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java]: That was a great idea, by changing this to use a json object I was able to remove the RawJsonValue hack I added in a while back.

File: src/main/java/bio/terra/cda/app/service/QueryService.java [hunk 2]
```diff
@@ -57,45 +66,90 @@ private Job runJob(Job queryJob) {
...
+    final List<JsonNode> jsonData = new ArrayList<>();
     /** For each system, the number of rows in jsonData that have data from that system. */
     final Map<Source, Integer> resultsCount = new EnumMap<>(Source.class);
+
+     /** Traverse the json data and collect the number of systems data present in resultsCount. */
+    private void generateUsageData() {
+      // Each node is a single row in the result.
+      for (JsonNode jsonNode : jsonData) {
+        List<String> systems = jsonNode.findValuesAsText("system");
+        Arrays.stream(Source.values())
```
Comment (nmalfroy) [inline src/main/java/bio/terra/cda/app/service/QueryService.java:81]: Are you worried about the case where `generateUsageData` gets called multiple times?  That could increase the counts and I just want to make sure that's expected.  Do you need to have a `resultsCount.clear()` in the beginning?  And if this is called from an endpoint, you probably need this in a `synchronized` since I don't think this is threadsafe

File: src/main/java/bio/terra/cda/app/service/QueryService.java [hunk 3]
```diff
@@ -57,45 +66,90 @@ private Job runJob(Job queryJob) {
...
-        results.jsonData.add(rowData);
-        Arrays.stream(Source.values())
-            .forEach(
-                s -> {
-                  // Each row can match one or more system.
-                  if (s.match(rowData)) {
-                    results.resultsCount.put(s, results.resultsCount.getOrDefault(s, 0) + 1);
-                  }
-                });
+        results.jsonData.add(
```
Comment (nmalfroy) [inline src/main/java/bio/terra/cda/app/service/QueryService.java:145]: I'm sort of surprised...did `objectMapper.readValue(FieldValue.of(FieldValue.Attribute.RECORD, row), JsonNode.class)` not do the trick?

File: src/main/java/bio/terra/cda/app/service/QueryService.java [hunk 4]
```diff
@@ -57,45 +66,90 @@ private Job runJob(Job queryJob) {
...
+          default:
+            // Primitive types other than boolean and numeric are represented as strings.
+            return new TextNode(value.getStringValue());
+        }
+      default:
+        throw new RuntimeException("Unknown field value type: " + value.getAttribute());
+    }
   }
 
   private Results getJobResults(Job queryJob) {
```
Comment (nmalfroy) [inline src/main/java/bio/terra/cda/app/service/QueryService.java:135]: I think you may want a unit test for this to validate the serialization

**Review by nmalfroy — COMMENTED** [review]
Just a couple of comments that could have a lot to do with my lack of understanding of the code

File: src/main/java/bio/terra/cda/app/service/QueryService.java (hunk 2 above)
Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:81]: The usage data is only used for logging the current request and is allocated once per every request, so there's no thread issue here. The various refactorings have made this less clear, so I'm going to get rid of the `Results` object and the lifetime of the usage should be more apparent.

File: src/main/java/bio/terra/cda/app/service/QueryService.java (hunk 3 above)
Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:145]: Not sure how that would work. `readValue()` is used to convert text to a JSON object, and but what we have here is a bigquery object, we don't have the source JSON that bigquery used to create the table result.

Comment (nmalfroy) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:145]: Shoot, sorry, I was doing it backwards.  I meant `objectMapper.writeObjectAsString(FieldValue.of(FieldValue.Attribute.RECORD, row))`. That would spit out the actual json string, which is a little different but might simplify the overall approach

Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:145]: ObjectMapper doesn't know how to convert a google field value to a json string, I get the error:
```Method threw 'com.fasterxml.jackson.databind.JsonMappingException' exception.```
 It's possible there's a way to intercept the raw json data coming back from the API, I can take another look at that.

File: src/main/java/bio/terra/cda/app/service/QueryService.java [hunk 5]
```diff
@@ -28,9 +38,14 @@
 
   private static final Logger logger = LoggerFactory.getLogger(QueryService.class);
 
-  final BigQuery bigQuery = BigQueryOptions.getDefaultInstance().getService();
+  final BigQuery bigQuery = BigQueryOptions.newBuilder().setProjectId("gdc-bq-sample").build().getService();
```
Comment (nmalfroy) [inline src/main/java/bio/terra/cda/app/service/QueryService.java:41]: Did you mean to hard-code this?

File: src/main/java/bio/terra/cda/app/service/QueryService.java [hunk 6]
```diff
@@ -52,51 +67,66 @@ private Job runJob(Job queryJob) {
...
-      return s.contains(match);
+  /**
+   * Convert a BQ value to a json node.
+   *
+   * @param value the value to convert
+   * @param field the schema field for the value
+   * @return a json node for the value
+   */
+  @VisibleForTesting
+  protected JsonNode valueToJson(FieldValue value, Field field) {
```
Comment (nmalfroy) [inline src/main/java/bio/terra/cda/app/service/QueryService.java:78]: I think it's possible to `value` to be null so you may want to add a check for that

File: src/main/java/bio/terra/cda/app/service/QueryService.java (hunk 5 above)
Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:41]: Yes, for now it's OK, but in the long term we'll want to create an injectable object for the bigquery service, and the project ID will be a configuration property.

File: src/main/java/bio/terra/cda/app/service/QueryService.java (hunk 6 above)
Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:78]: Actually `null` is handled by a `value` whose attribute is `PRIMITIVE` and `isNull()` returns `true`.

https://github.com/CancerDataAggregator/cda-service/blob/ps-issue-67-duplicate-json-keys/src/main/java/bio/terra/cda/app/service/QueryService.java#L96

If this check isn't done, then you get an NPE when calling `getStringValue()` or `getValue()`

File: src/main/java/bio/terra/cda/app/service/QueryService.java (hunk 5 above)
Comment (pshapiro4broad) [reply src/main/java/bio/terra/cda/app/service/QueryService.java:41]: https://github.com/CancerDataAggregator/cda-service/issues/72

**Review by nmalfroy — APPROVED** [review]
Looks great!  Thanks for indulging my questions!
